---
title: "Analiza danych odnośnie oczekiwanej długości życia"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---
Postanowiliśmy rozważyć jak PKB per capita wpływa na przewidywaną długość życia. Nasze rozważania oparliśmy o dane statystyczne ze strony https://databank.worldbank.org/ 
Rozważymy dane pochodzące z kilku krajów. Wybrane kraje to: USA, Polska, Chiny, Indie, Brazylia, Nigeria, Australia. Wybór tych państw był podyktowany ich znaczeniem na arenie międzynarodowej, liczbą ludności, oraz pragnieniem uwzględnienia różnych rejonów świata.



Źródło dla danych traktujących o przewidywanej długości życia:(1) United Nations Population Division. World Population Prospects: 2019 Revision, or derived from male and female life expectancy at birth from sources such as: (2) Census reports and other statistical publications from national statistical offices, (3) Eurostat: Demographic Statistics, (4) United Nations Statistical Division. Population and Vital Statistics Reprot (various years), (5) U.S. Census Bureau: International Database, and (6) Secretariat of the Pacific Community: Statistics and Demography Programme.
Metodologia pomiaru: Przewidywana długośc życia w czasie narodzin jest tutaj średnią przewidywaną liczbą lat życia noworodka jeśli przewidywany wzór śmiertelności pozostanie taki sam w przyszłości.
Odzwierciedla średnią wieku śmierci populacji i tworzy wzorzec śmiertelności, który przeważa we wszystkich grupach wiekowych w danym roku. Dlatego nie odzwierciedla wzoru umieralności, którego dana osoba faktycznie doświadczy podczas swojego życia.
Wysoka śmiertelność w młodych grupach wiekowych znacznie obniża oczekiwaną długość życia. Jeśli jednak dana osoba przeżyje dzieciństwo, może żyć znacznie dłużej. Na przykład w populacji, której oczekiwana długość życia wynosi 50 lat, może być niewiele osób umierających w wieku 50 lat. Oczekiwana długość życia w chwili urodzenia może być niska ze względu na wysoką śmiertelność w dzieciństwie, tak że gdy osoba przeżyje swoje dzieciństwo, może żyć znacznie dłużej niż 50 lat.


Źródło dla danych traktujących o produkcie krajowym brutto per capita: World Bank national accounts data, and OECD National Accounts data files.
Produkt Krajowy Brutto per capita - to wskaźnik zamożności w przeliczeniu na jednego mieszkańca. Jest on obliczany jako PKB / liczbę mieszkańców państwa
PKB opisuje zagregowaną wartość dóbr i usług finalnych wytworzonych przez narodowe i zagraniczne czynniki produkcji na terenie danego kraju w określonej jednostce czasu (najczęściej w ciągu roku). PKB jest miarą wielkości gospodarki.

```{R}
# Loading data
LE <- read.csv("LE.csv")
GDP <- read.csv("GDP.csv")
Countries <- c('USA', 'DEU', 'CHN', 'IND', 'BRA', 'NGA', 'AUS')

le <- function(country_code) {
  rok <- 1960:2019
  le <- as.numeric(LE[LE$Country.Code == country_code,][-c(1:4)][1:60])
  data.frame(rok, le)
}

gdp <- function(country_code) {
  rok <- 1960:2019
  gdp <- as.numeric(GDP[GDP$Country.Code == country_code,][-c(1:4)][1:60])
  data.frame(rok, gdp)
}

data <- function(country_code) {
  rok <- 1960:2019
  le <- as.numeric(LE[LE$Country.Code == country_code,][-c(1:4)][1:60])
  gdp <- as.numeric(GDP[GDP$Country.Code == country_code,][-c(1:4)][1:60])
  data.frame(rok, gdp, le)
}

```


```{R}
boxplot(LE[ -c(1:4) ])
```
Wykres przedstawia oczekiwaną długość życia na świecie w latach 1960 - 2018. Oczekiwana długość życia w danym roku przedstawiona jest za pomocą wykresu pudełkowego. Widoczny jest wyraźny trend rosnący. Interesujące wydają się lata 80-te i 90-te, gdzie z wykresu odczytać można wyraźne wartości odstające. "Dołek" z lat 70-tych to oczekiwana długość życia w Kambodży pod rządami Pol Pota (1975 - 1979), natomiast w latach 90-tych widać oczekiwaną długość życia w Rwandzie obniżoną w stosunku do lat poprzednich z powodu ludobójstwa, które miało miejsce w tym kraju w roku 1994. 

Wykres pokazujący PKB per capita dla różnych krajów świata od roku 1960 do 2019. 
=======
```{R}
plot(gdp('USA'), main="PKB per capita w USA", xlab="Rok", ylab="PKB per capita w USD")
plot(gdp('AUT'), main="PKB per capita w Austrii", xlab="Rok", ylab="PKB per capita w USD")
plot(gdp('CHN'), main="PKB per capita w Chinach", xlab="Rok", ylab="PKB per capita w USD")
plot(gdp('IND'), main="PKB per capita w Indiach", xlab="Rok", ylab="PKB per capita w USD")
plot(gdp('BRA'), main="PKB per capita w Brazylii", xlab="Rok", ylab="PKB per capita w USD")
plot(gdp('NGA'), main="PKB per capita w Nigerii", xlab="Rok", ylab="PKB per capita w USD")
plot(gdp('AUS'), main="PKB per capita w Australii", xlab="Rok", ylab="PKB per capita w USD")
```


Poniższe wykresy przedstawiają oczekiwane długości życia w wybranych państwach. Można zauważyć wyraźny trend wzrostowy w większości krajów. Wyjątkiem są Stany Zjednoczone, gdzie w ostatnich latach następuje niewielki spadek.

```{R}
plot(le('USA'), main="Oczekiwana długość życia w USA", xlab="Rok", ylab="Lata")

plot(le('AUT'), main="Oczekiwana długość życia w Austrii", xlab="Rok", ylab="Lata")

plot(le('CHN'), main="Oczekiwana długość życia w Chinach", xlab="Rok", ylab="Lata")

plot(le('IND'), main="Oczekiwana długość życia w Indiach", xlab="Rok", ylab="Lata")

plot(le('BRA'), main="Oczekiwana długość życia w Brazylii", xlab="Rok", ylab="Lata")

plot(le('NGA'), main="Oczekiwana długość życia w Nigerii", xlab="Rok", ylab="Lata")

plot(le('AUS'), main="Oczekiwana długość życia w Australii", xlab="Rok", ylab="Lata")
```



```{R}
usa <- data('USA')
plot(usa$le~usa$gdp, main="Zależność przewidywanych lat życia w USA od PKB per capita", xlab="USD", ylab="Przewidywana długość życia")
abline(lm ( usa$le ~ usa$gdp ))
cor(usa$gdp,usa$le, use="complete.obs")
summary(lm ( usa$le ~ usa$gdp ))
```

 
Współczynnik korelacji przewidywanych lat życia w USA od PKB per capita dla USA

```{R}
aut <- data('AUT')
plot(aut$le~aut$gdp, main="Zależność przewidywanych lat życia w Austrii od PKB per capita", xlab="USD", ylab="Przewidywana długość życia")
abline(lm ( aut$le ~ aut$gdp ))
cor(aut$gdp,aut$le, use="complete.obs")
summary(lm ( aut$le ~ aut$gdp ))
``` 

Współczynnik korelacji przewidywanych lat życia od PKB per capita w Austrii

```{R}
CHN <- data('CHN')
plot(CHN$le~CHN$gdp, main="Zależność przewidywanych lat życia w Chinach od PKB per capita", xlab="USD", ylab="Przewidywana długość życia")
abline(lm ( CHN$le ~ CHN$gdp ))
cor(CHN$gdp,CHN$le, use="complete.obs")
summary(lm ( aut$le ~ aut$gdp ))
```

Współczynnik korelacji przewidywanych lat życia od PKB per capita w Chinach

```{R}
IND <- data('IND')
plot(IND$le~IND$gdp, main="Zależność przewidywanych lat życia w Indiach od PKB per capita", xlab="USD", ylab="Przewidywana długość życia")
abline(lm ( IND$le ~ IND$gdp ))
cor(IND$gdp,IND$le, use="complete.obs")
summary(lm ( IND$le ~ IND$gdp ))
```

Współczynnik korelacji przewidywanych lat życia od PKB per capita w Indiach

```{R}
BRA <- data('BRA')
plot(BRA$le~BRA$gdp, main="Zależność przewidywanych lat życia w Brazylii od PKB per capita", xlab="USD", ylab="Przewidywana długość życia")
abline(lm ( BRA$le ~ BRA$gdp ))
cor(BRA$gdp,BRA$le, use="complete.obs")
summary(lm ( BRA$le ~ BRA$gdp ))
```

Współczynnik korelacji przewidywanych lat życia od PKB per capita w Brazylii

```{R}
NGA <- data('NGA')
plot(NGA$le~NGA$gdp, main="Zależność przewidywanych lat życia w Nigerii od PKB per capita", xlab="USD", ylab="Przewidywana długość życia")
abline(lm ( NGA$le ~ NGA$gdp ))
cor(NGA$gdp,NGA$le, use="complete.obs")
summary(lm ( NGA$le ~ NGA$gdp ))
```

Współczynnik korelacji przewidywanych lat życia od PKB per capita w Nigerii

```{R}
AUS <- data('AUS')
plot(AUS$le~AUS$gdp, main="Zależność przewidywanych lat życia w Australii od PKB per capita", xlab="USD", ylab="Przewidywana długość życia")
abline(lm ( AUS$le ~ AUS$gdp ))
cor(AUS$le, AUS$gdp, use="complete.obs")
summary(lm ( AUS$le ~ AUS$gdp ))
```

Współczynnik korelacji przewidywanych lat życia od PKB per capita w Australii


## Wnioski

Dla wszystkich siedmiu wykresów przedstawiających zależność przewidywanych lat życia od PKB na mieszkańca współczynnik kierunkowy regresji liniowej przyjął wartość dodatnią. Wartym odnotowania jest także wysoki współczynnik R^2 wspomnianych regresji. Wskazuje to, że są one dobrze dopasowane. Może to sugerować, że przy zwiększaniu się PKB na mieszkańca danego kraju rośnie także oczekiwana długość życia. 


### Źródła

Źródło dla danych traktujących o przewidywanej długości życia:
https://data.worldbank.org/indicator/SP.DYN.LE00.IN

źródło dla danych o PKB na osobę: 
https://data.worldbank.org/indicator/NY.GDP.PCAP.CD 

Wykorzystane narzędzia programistyczne

RStudio https://rstudio.com/

R Markdown https://rmarkdown.rstudio.com/
